version: 0.0.{build}
image: Visual Studio 2017
test: off
deploy: off
environment:
  TEST:
    secure: sUrXRaSNWZJ154sh4iOCjg==
  DOCKER_WRITTER_USERNAME: dnoyawritter
  DOCKER_WRITTER_PASSWORD:
    secure: CPdmv2DSokphYiqiE8eii4mz2v4exefw8SuWbRmgvStOFRsl0RkpdAfHgYnlci57

for:
  - branches:
      only:
        - master
        - INT
        - PRODTEST
        - MYTEST
    skip_non_tags: false
    skip_tags: true
    build_script:
      - ps: sh ./build-n-publish.sh --commit="$env:APPVEYOR_REPO_COMMIT" --name="$env:APPVEYOR_REPO_BRANCH" --platform=windows
  - branches:
      only:
        - /v\d+\.\d+\.\d+.*/
    skip_non_tags: true
    skip_tags: false
    build_script:
      - ps: sh ./build-n-publish.sh --commit="$env:APPVEYOR_REPO_COMMIT" --version="$env:APPVEYOR_REPO_TAG_NAME" --platform=windows
  - branches:
      only:
        - NOBRANCH
    skip_tags: true
    skip_branch_with_pr: true
    build_script:
      - ps: sh ./build-n-publish.sh --commit="$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT" --name=pr-"$env:APPVEYOR_PULL_REQUEST_NUMBER" --platform=windows
      # TODO: do not try to publish when DOCKER_WRITTER_PASSWORD is not defined (PRs from external forks)
