name: Build and publish Windows-based Docker image

on:

# Commented because we are not generating official builds with GitHub Actions
#  push:
#    branches:
#      - master
#      - INT
#      - PRODTEST
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+*'
#  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify code format (Linux Docker required)
        run: docker build --target verify-format --file Dockerfile.verify .
      - name: Verify .sh files (Linux Docker required)
        run: docker build --target verify-sh --file Dockerfile.verify .

  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Restore
        run: docker build --target restore .
      - name: Build
        run: docker build --target build .
      - name: Test
        run: docker build --target test .
      - name: Publish pre-release image from pull request
        if: ${{ github.event_name == 'pull_request' }}
        env:
          DOCKER_WRITTER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_WRITTER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        # By the moment it is building the merge commit, so github.sha is not a commit in the PR branch
        run: bash ./build-n-publish.sh --commit=${{ github.sha }} --name=pr-${{ github.event.number }} --platform=windows
      - name: Publish pre-release image from PRODTEST
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/PRODTEST' }}
        env:
          DOCKER_WRITTER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_WRITTER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: bash ./build-n-publish.sh --commit=${{ github.sha }} --name=PRODTEST --platform=windows
      - name: Publish pre-release image from INT
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/INT' }}
        env:
          DOCKER_WRITTER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_WRITTER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: bash ./build-n-publish.sh --commit=${{ github.sha }} --name=INT --platform=windows
      - name: Publish pre-release image from master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          DOCKER_WRITTER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_WRITTER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: bash ./build-n-publish.sh --commit=${{ github.sha }} --name=master --platform=windows
      - name: Publish final image from version tag
        if: ${{ github.event_name == 'push' && startsWith(github.ref,'refs/tags/v') }}
        env:
          DOCKER_WRITTER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_WRITTER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          GIT_REF: ${{ github.ref }}
        run: bash ./build-n-publish.sh --commit=${{ github.sha }} --platform=windows
