name: Build and publish Windows-based Docker image

on:

  pull_request:

jobs:

  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verify code format (Linux Docker required)
      run: docker build --target verify-format --file Dockerfile.verify .
    - name: Verify .sh files (Linux Docker required)
      run: docker build --target verify-sh --file Dockerfile.verify .

  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Restore
      run: docker build --target restore .
    - name: Build
      run: docker build --target build .
    - name: Test
      run: docker build --target test .
    - name: Publish pre-release image from pull request
      env:
        DOCKER_WRITTER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_WRITTER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      # By the moment it is building the merge commit, so github.sha is not a commit in the PR branch
      run: bash ./build-n-publish.sh --commit=${{ github.sha }} --name=pr-${{ github.event.number }} --platform=windows
